# Only non OpenGL components of Yocto/GL are built
# This Travis file is a heavily modified version of https://github.com/nlohmann/json

language: cpp

dist: xenial
sudo: required

matrix:
  include:

  - os: osx
    osx_image: xcode10

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
        packages: ['g++-7', 'ninja-build']

  # - os: linux
  #   compiler: clang
  #   env:
  #     - COMPILER=clang++-5.0
  #     - CMAKE_OPTIONS="-DYOCTO_OPENGL=OFF -DYOCTO_EMBREE=OFF"
  #   addons:
  #     apt:
  #       # sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0', 'sourceline': 'deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main']
  #       # packages: ['g++-6', 'clang-5.0', 'ninja-build', 'libgl1-mesa-dev', 'libglew-dev', 'libglfw3-dev']
  #       sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
  #       packages: ['g++-7', 'clang-5.0', 'ninja-build']

  # - os: linux
  #   compiler: gcc
  #   env:
  #     - COMPILER=g++-8
  #     - CMAKE_OPTIONS="-DYOCTO_OPENGL=OFF -DYOCTO_EMBREE=OFF"
  #   addons:
  #     apt:
  #       # sources: ['ubuntu-toolchain-r-test', 'sourceline': 'deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main']
  #       # packages: ['g++-7', 'ninja-build', 'libgl1-mesa-dev', 'libglew-dev', 'libglfw3-dev']
  #       sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
  #       packages: ['g++-8', 'ninja-build']

branches:
  only:
    - master
    - devel

script:
  # get CMake and Ninja (only for systems with brew - macOS)
  - |
     if [[ (-x $(which brew)) ]]; then
       brew update
       brew install cmake ninja
       cmake --version
     fi

  # make sure CXX is correctly set
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

  # show OS/compiler version
  - uname -a
  - $CXX --version

  # compile and execute unit tests
  - mkdir -p build && cd build
  - cmake .. ${CMAKE_OPTIONS} -GNinja && cmake --build . --config Release
  # - if [[ (-x $(which brew)) ]]; then ctest -j 4; fi
  # - ctest -j 4
  - cd ..
